image:
  file: .gitpod/Dockerfile

tasks:
  - name: Install dependencies and compile source code
    init: |
      mix local.hex --force
      mix local.rebar --force
      mix deps.get
      mix compile
      MIX_ENV=test mix compile
      
  - name: Start development server
    command: iex -S mix phx.server
    openMode: tab-after

ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - benvp.vscode-hex-pm-intellisense
    - bradlc.vscode-tailwindcss
    - elixir-lsp.elixir-ls
    - esbenp.prettier-vscode
