image:
  file: .gitpod/Dockerfile
    
tasks:
  - name: Install dependencies
    init: mix deps.get
  - name: Compile source code
    init: |
      mix compile
      MIX_ENV=test mix compile
    
ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - benvp.vscode-hex-pm-intellisense
    - bradlc.vscode-tailwindcss
    - elixir-lsp.elixir-ls
    - esbenp.prettier-vscode
