image:
  file: .gitpod/Dockerfile

ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - benvp.vscode-hex-pm-intellisense
    - bradlc.vscode-tailwindcss
    - elixir-lsp.elixir-ls
    - esbenp.prettier-vscode
