image:
  file: .gitpod/Dockerfile

tasks:
  - name: Run tests
    init: |
      mix deps.get
      MIX_ENV=test mix compile
    command: mix test
    openMode: tab-after

  - name: Start development server
    init: |
      mix deps.get
      mix compile
      mix ecto.create
    command: iex -S mix phx.server
    openMode: tab-after

ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - benvp.vscode-hex-pm-intellisense
    - bradlc.vscode-tailwindcss
    - elixir-lsp.elixir-ls
    - esbenp.prettier-vscode
