image:
  file: .gitpod/Dockerfile

tasks:
  - name: "Phoenix Dev Server"
    init: |
      mix setup
      mix compile
    command: iex -S mix phx.server

ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - benvp.vscode-hex-pm-intellisense
    - bradlc.vscode-tailwindcss
    - elixir-lsp.elixir-ls
    - esbenp.prettier-vscode
