services:
  phoenix:
    container_name: phoenix
    build:
      context: .
      dockerfile: "phoenix-dockerfile"
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspace:cached
      - elixir-build:/workspace/_build
      - elixir-deps:/workspace/deps
      - elixir-ls:/workspace/.elixir_ls

  postgres:
    container_name: postgres
    image: "postgres:15.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - ../db_data:/var/lib/postgresql/data

volumes:
  elixir-build:
  elixir-deps:
  elixir-ls:
