services:
  phoenix:
    container_name: phoenix
    build:
      context: .
      dockerfile: "phoenix-dockerfile"
    stdin_open: true
    tty: true
    working_dir: /usr/src/hap
    volumes:
      - ..:/usr/src/hap
      - elixir-build:/usr/src/hap/_build
      - elixir-deps:/usr/src/hap/deps
      - elixir-ls:/usr/src/hap/.elixir_ls

  postgres:
    container_name: postgres
    image: "postgres:15.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - ../db_data:/var/lib/postgresql/data

volumes:
  elixir-build:
  elixir-deps:
  elixir-ls:
